name = "glenvy"
version = "0.5.1"
description = "A pleasant way to interact with your environment."
licences = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "glenvy" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_erlang = "~> 0.24"
nibble = "~> 1.0"
simplifile = "~> 1.2"

[dev-dependencies]
gleeunit = "~> 1.0"
