name = "glenvy"
version = "0.6.1"
description = "A pleasant way to interact with your environment variables."
licenses = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "glenvy" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_erlang = "~> 0.25"
nibble = "~> 1.1"
simplifile = "~> 1.7"

[dev-dependencies]
gleeunit = "~> 1.0"
